name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: '5.0.x'
           
      - name: Create Artifacts Directory
        run: mkdir artifacts
    
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: Elskom/publish-nuget@main
        with:
          PROJECT_FILE_PATH: '**/*.csproj'
          PACKAGE_PATH: artifacts/
          NUGET_KEY: ${{secrets.NUGET_KEY}}
